Use a less heavyweight method to force color
OSAS/ansible-role-ansible_bastion pull request #45
Opened 2017-02-26 13:17 UTC by mscherer

force_color = True was added to make sure the colors
are displayed by git post commit hooks. However, one
unplanned side effect is that colors are also displayed
in mail sent by cron, thuis making them hard to read.

So instead of forcing for all runs, we should make
that only for the sudo runs.

2017-02-27 09:40 UTC, duck-rh requested changes
The envvar is ANSIBLE_FORCE_COLOR, so there is a typo

2017-02-27 10:35 UTC, mscherer commented
indeed.

2017-03-06 16:15 UTC, mscherer commented
So it seems that I did the change (after reading the commit again a few time), so I am gonna merge it.

2017-03-06 16:15 UTC, merged

2017-03-06 17:11 UTC, duck-rh commented
It's fine